pipline{
    agent any 
    stage {
        stage("Run Script"){
            steps {
                dir("Task2"){
                sh "Task2/deploy.sh"
                }
            }
        }
    }
}